---
title: "Starting Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("data.table")

```

```{r}
# Load the datasets
riskdata <- read.csv("RISKFACTORSANDACCESSTOCARE.csv")
demogdata <- read.csv("DEMOGRAPHICS.csv")

bddata <- read.csv("MEASURESOFBIRTHANDDEATH.csv")

#sqldf::sqldf("select count(*) from deathdata where deathdata.A_Wh_Comp = -1111")
```

```{r}
install.packages("zoo")
library("zoo")
```


```{r}
deathdata <- read.csv("LEADINGCAUSESOFDEATH.csv")

deathdata[deathdata==-1111]<-0
deathdata[deathdata==-1111.1]<-0
deathdata[deathdata==-1]<-0
deathdata[deathdata==-2222]<-0
deathdata[deathdata==-2222.2]<-0
deathdata[deathdata==-2]<-0

#for(i in 1:ncol(deathdata)){
#  deathdata[is.na(deathdata[,i]), i] <- mean(deathdata[,i], na.rm = TRUE)
#}

```



```{r}
# Deal with missing values
# First replace all -1111, -1111.1, -1, -2222.2, -2222, -2 with ?, so that Weka can #read it, and then a filter can be applied to impute the mean of the attributes into #the missing value spot

# I know I could have merged them and then changed the values to NA, but I have a good reason for doing it this way, as I'll be making seperate merges for each race

riskdata[riskdata==-1111]<-NA
riskdata[riskdata==-1111.1]<-NA
riskdata[riskdata==-1]<-NA
riskdata[riskdata==-2222]<-NA
riskdata[riskdata==-2222.2]<-NA
riskdata[riskdata==-2]<-NA

bddata[bddata==-1111]<-NA
bddata[bddata==-1111.1]<-NA
bddata[bddata==-1]<-NA
bddata[bddata==-2222]<-NA
bddata[bddata==-2222.2]<-NA
bddata[bddata==-2]<-NA

demogdata[demogdata==-1111]<-NA
demogdata[demogdata==-1111.1]<-NA
demogdata[demogdata==-1]<-NA
demogdata[demogdata==-2222]<-NA
demogdata[demogdata==-2222.2]<-NA
demogdata[demogdata==-2]<-NA



# Eventually we will replace the missing values with the mean of their column in Weka. (not yet though) 

```

```{r}

```


```{r}
# Deathdata cleaning 
# This dataset has mostly NA values but can be still used if we set those to 0, and add up that counties numbers to a total regardless of age (i.e. Age1_Cancer + Age2_Cancer +..)
# Then drop the former columns

deathdata2 <- deathdata

#attach(deathdata2)

```

```{r}
# Remove CI columns
deathdata2<-deathdata2[(grep("^CI", names(deathdata2), invert = TRUE))]

# Cancer 

# Sum the cancers to 
deathdata2[, "Whi_Cancer"] <- deathdata2$B_Wh_Cancer + deathdata2$C_Wh_Cancer + deathdata2$D_Wh_Cancer + deathdata2$E_Wh_Cancer + deathdata2$F_Wh_Cancer

deathdata2$B_Wh_Cancer <- NULL
deathdata2$C_Wh_Cancer <- NULL
deathdata2$D_Wh_Cancer <- NULL
deathdata2$E_Wh_Cancer <- NULL
deathdata2$F_Wh_Cancer <- NULL


# Check is good.
#deathdata2$Whi_Cancer[1]
#deathdata2$B_Wh_Cancer[1] + deathdata2$C_Wh_Cancer[1] + deathdata2$D_Wh_Cancer[1] + deathdata2$E_Wh_Cancer[1] + #deathdata2$F_Wh_Cancer[1]

deathdata2[, "Blk_Cancer"] <- deathdata2$B_Bl_Cancer + deathdata2$C_Bl_Cancer + deathdata2$D_Bl_Cancer + deathdata2$E_Bl_Cancer + deathdata2$F_Bl_Cancer

deathdata2$B_Bl_Cancer <- NULL
deathdata2$C_Bl_Cancer <- NULL
deathdata2$D_Bl_Cancer <- NULL
deathdata2$E_Bl_Cancer <- NULL
deathdata2$F_Bl_Cancer <- NULL

deathdata2[, "His_Cancer"] <- deathdata2$B_Hi_Cancer + deathdata2$C_Hi_Cancer + deathdata2$D_Hi_Cancer + deathdata2$E_Hi_Cancer + deathdata2$F_Hi_Cancer

deathdata2$B_Hi_Cancer <- NULL
deathdata2$C_Hi_Cancer <- NULL
deathdata2$D_Hi_Cancer <- NULL
deathdata2$E_Hi_Cancer <- NULL
deathdata2$F_Hi_Cancer <- NULL

deathdata2[, "Oth_Cancer"] <- deathdata2$B_Ot_Cancer + deathdata2$C_Ot_Cancer + deathdata2$D_Ot_Cancer + deathdata2$E_Ot_Cancer + deathdata2$F_Ot_Cancer

deathdata2$B_Ot_Cancer <- NULL
deathdata2$C_Ot_Cancer <- NULL
deathdata2$D_Ot_Cancer <- NULL
deathdata2$E_Ot_Cancer <- NULL
deathdata2$F_Ot_Cancer <- NULL

# Now for Comp

deathdata2[, "Whi_Comp"] <- deathdata2$A_Wh_Comp 

deathdata2$A_Wh_Comp <- NULL

deathdata2[, "Blk_Comp"] <- deathdata2$A_Bl_Comp 

deathdata2$A_Bl_Comp <- NULL


deathdata2[, "His_Comp"] <- deathdata2$A_Hi_Comp 

deathdata2$A_Hi_Comp <- NULL


deathdata2[, "Oth_Comp"] <- deathdata2$A_Ot_Comp 

deathdata2$A_Ot_Comp <- NULL

# Now BirthDef

deathdata2[, "Whi_BirthDef"] <- deathdata2$A_Wh_BirthDef 

deathdata2$A_Wh_BirthDef <- NULL

deathdata2[, "Blk_BirthDef"] <- deathdata2$A_Bl_BirthDef 

deathdata2$A_Bl_BirthDef <- NULL

deathdata2[, "His_BirthDef"] <- deathdata2$A_Hi_BirthDef 

deathdata2$A_Hi_BirthDef <- NULL

deathdata2[, "Oth_BirthDef"] <- deathdata2$A_Ot_BirthDef 

deathdata2$A_Ot_BirthDef <- NULL

# Injury

deathdata2[, "Whi_Injury"] <- deathdata2$B_Wh_Injury + deathdata2$C_Wh_Injury + deathdata2$D_Wh_Injury

deathdata2$B_Wh_Injury <- NULL
deathdata2$C_Wh_Injury <- NULL
deathdata2$D_Wh_Injury <- NULL

deathdata2[, "Blk_Injury"] <- deathdata2$B_Bl_Injury + deathdata2$C_Bl_Injury + deathdata2$D_Bl_Injury

deathdata2$B_Bl_Injury <- NULL
deathdata2$C_Bl_Injury <- NULL
deathdata2$D_Bl_Injury <- NULL

deathdata2[, "His_Injury"] <- deathdata2$B_Hi_Injury + deathdata2$C_Hi_Injury + deathdata2$D_Hi_Injury

deathdata2$B_Hi_Injury <- NULL
deathdata2$C_Hi_Injury <- NULL
deathdata2$D_Hi_Injury <- NULL

deathdata2[, "Oth_Injury"] <- deathdata2$B_Ot_Injury + deathdata2$C_Ot_Injury + deathdata2$D_Ot_Injury

deathdata2$B_Ot_Injury <- NULL
deathdata2$C_Ot_Injury <- NULL
deathdata2$D_Ot_Injury <- NULL

# Homicide

deathdata2[, "Whi_Homicide"] <- deathdata2$B_Wh_Homicide + deathdata2$C_Wh_Homicide + deathdata2$D_Wh_Homicide

deathdata2$B_Wh_Homicide <- NULL
deathdata2$C_Wh_Homicide <- NULL
deathdata2$D_Wh_Homicide <- NULL

deathdata2[, "Blk_Homicide"] <- deathdata2$B_Bl_Homicide + deathdata2$C_Bl_Homicide + deathdata2$D_Bl_Homicide

deathdata2$B_Bl_Homicide <- NULL
deathdata2$C_Bl_Homicide <- NULL
deathdata2$D_Bl_Homicide <- NULL

deathdata2[, "His_Homicide"] <- deathdata2$B_Hi_Homicide + deathdata2$C_Hi_Homicide + deathdata2$D_Hi_Homicide

deathdata2$B_Hi_Homicide <- NULL
deathdata2$C_Hi_Homicide <- NULL
deathdata2$D_Hi_Homicide <- NULL

# Oth_Homicide not behaving. Find out why. Solved.
deathdata2[, "Oth_Homicide"] <- deathdata2$B_Ot_Homicide + deathdata2$C_Ot_homicide + deathdata2$D_Ot_Homicide

deathdata2$B_Ot_Homicide <- NULL
deathdata2$C_Ot_homicide <- NULL
deathdata2$D_Ot_Homicide <- NULL

# Suicide

deathdata2[, "Whi_Suicide"] <- deathdata2$C_Wh_Suicide + deathdata2$D_Wh_Suicide

deathdata2$C_Wh_Suicide <- NULL
deathdata2$D_Wh_Suicide <- NULL

deathdata2[, "Blk_Suicide"] <- deathdata2$C_Bl_Suicide + deathdata2$D_Bl_Suicide

deathdata2$C_Bl_Suicide <- NULL
deathdata2$D_Bl_Suicide <- NULL

deathdata2[, "His_Suicide"] <- deathdata2$C_Hi_Suicide + deathdata2$D_Hi_Suicide

deathdata2$C_Hi_Suicide <- NULL
deathdata2$D_Hi_Suicide <- NULL

deathdata2[, "Oth_Suicide"] <- deathdata2$C_Ot_Suicide + deathdata2$D_Ot_Suicide

deathdata2$C_Ot_Suicide <- NULL
deathdata2$D_Ot_Suicide <- NULL

# Heart Disease

deathdata2[, "Whi_HeartDis"] <- deathdata2$D_Wh_HeartDis + deathdata2$E_Wh_HeartDis + deathdata2$F_Wh_HeartDis

deathdata2$D_Wh_HeartDis <- NULL
deathdata2$E_Wh_HeartDis <- NULL
deathdata2$F_Wh_HeartDis <- NULL

deathdata2[, "Blk_HeartDis"] <- deathdata2$D_Bl_HeartDis + deathdata2$E_Bl_HeartDis + deathdata2$F_Bl_HeartDis

deathdata2$D_Bl_HeartDis <- NULL
deathdata2$E_Bl_HeartDis <- NULL
deathdata2$F_Bl_HeartDis <- NULL

deathdata2[, "His_HeartDis"] <- deathdata2$D_Hi_HeartDis + deathdata2$E_Hi_HeartDis + deathdata2$F_Hi_HeartDis

deathdata2$D_Hi_HeartDis <- NULL
deathdata2$E_Hi_HeartDis <- NULL
deathdata2$F_Hi_HeartDis <- NULL

deathdata2[, "Oth_HeartDis"] <- deathdata2$D_Ot_HeartDis + deathdata2$E_Ot_HeartDis + deathdata2$F_Ot_HeartDis

deathdata2$D_Ot_HeartDis <- NULL
deathdata2$E_Ot_HeartDis <- NULL
deathdata2$F_Ot_HeartDis <- NULL

# HIV

deathdata2[, "Whi_HIV"] <- deathdata2$D_Wh_HIV

deathdata2$D_Wh_HIV <- NULL

deathdata2[, "Blk_HIV"] <- deathdata2$D_Bl_HIV

deathdata2$D_Bl_HIV <- NULL

deathdata2[, "His_HIV"] <- deathdata2$D_Hi_HIV

deathdata2$D_Hi_HIV <- NULL

deathdata2[, "Oth_HIV"] <- deathdata2$D_Ot_HIV

deathdata2$D_Ot_HIV <- NULL

# Done.


```

```{r}
sum(deathdata2$Blk_Cancer)
```


```{r}
# remove CI attributes from data
bddata<-bddata[(grep("^CI", names(bddata), invert = TRUE))]

demogdata<-demogdata[(grep("^CI", names(demogdata), invert = TRUE))]

riskdata<-riskdata[(grep("^CI", names(riskdata), invert = TRUE))]


```


```{r}

(colSums(is.na(bddata))/3141)*100
#(colSums(is.na(demogdata))/3141)*100
#(colSums(is.na(riskdata))/3141)*100

#riskdata <- riskdata[complete.cases(riskdata[, ]), ]



#(colSums(is.na(riskdata))/3141)*100
```

```{r}
# Merge the datasets
mrg1 <- merge(riskdata, demogdata, sort=TRUE)
mrgn <- merge(deathdata2, mrg1, sort=TRUE)
mrg2 <- merge(mrgn, bddata, sort=TRUE)
```


```{r}


# Remove rows based on NA values in riskdata (do this after merge!!)
mrg3 <- mrg2[complete.cases(mrg2[, c("No_Exercise", "Few_Fruit_Veg", "High_Blood_Pres", "Obesity", "Smoker")]), ]

# FORFEITED METHOD (for now)
# Just impute the mean for NA's
#mrg3 <- mrg2

#for(i in 1:ncol(mrg3)){
#  mrg3[is.na(mrg3[,i]), i] <- mean(mrg3[,i], na.rm = TRUE)
#}

```

```{r}
(colSums(is.na(mrg3))/1434)*100
```
```{r}
mrg4 <- mrg3
mrg4$IM_Bl_Non_Hisp <- NULL
mrg4$IM_Bl_Non_Hisp_Ind <- NULL
mrg4$IM_Hisp <- NULL
mrg4$IM_Hisp_Ind <- NULL
mrg4$Homicide <- NULL
mrg4$Homicide_Ind <- NULL
```

```{r}

```

```{r}

```


```{r}

```



```{r}
# Now remove rows with any instances of NA
mrg5 <- mrg4[complete.cases(mrg4),]

 

#(colSums(is.na(mrg5))/1261)*100
# Good: No more missing values, and still 1261 rows left.
```



```{r}
qqnorm(mrg5$Brst_Cancer, main = "Breast Cancer")
qqline(mrg5$Brst_Cancer)

qqnorm(mrg5$Lung_Cancer, main = "Lung Cancer")
qqline(mrg5$Lung_Cancer)

qqnorm(mrg5$Col_Cancer, main = "Colon Cancer")
qqline(mrg5$Col_Cancer)

qqnorm(mrg5$CHD, main = "Heart Disease")
qqline(mrg5$CHD)
# All normal

qqnorm(mrg5$Whi_Cancer, main = "Death from Cancer (White)")
qqline(mrg5$Whi_Cancer)

qqnorm(mrg5$Blk_HeartDis, main = "Death from Heart Disease (Black)")
qqline(mrg5$Blk_HeartDis)

qqnorm(mrg5$No_Exercise, main = "No Exercise") 
qqline(mrg5$No_Exercise)





```



```{r}
# Take out ind, max and min attributes
mrg5 <- mrg4
mrg5<-mrg5[(grep("._Ind", names(mrg5), invert = TRUE))]
mrg5<-mrg5[(grep("^Max", names(mrg5), invert = TRUE))]
mrg5<-mrg5[(grep("^Min", names(mrg5), invert = TRUE))]
                                 
```

```{r}

```



```{r}
# write to arff to use in Weka to check for normal distribution
#library(foreign)
#write.arff(mrg5, file="CLEANDATA1.arff") # identified non-normal attributes
```


```{r}
# Take out categorical variables for correlative analysis
mrg6 <- mrg5

mrg6[, c("State_FIPS_Code", "County_FIPS_Code", "CHSI_County_Name", "CHSI_State_Name", "CHSI_State_Abbr", "Strata_ID_Number", "Strata_Determining_Factors", "MOBD_Time_Span", "LCD_Time_Span")] <- NULL

```

```{r}
sapply(mrg6, var)
```

```{r}
# Check some correlations
mrg7 <- cor(mrg6)

mrg7[lower.tri(mrg7,diag=TRUE)]=NA  
mrg7=as.data.frame(as.table(mrg7))  
mrg7=mrg7[order(-abs(mrg7$Freq)),]   

mrg7
```


```{r}

#corrplot::corrplot(mrg6)
# Hmm... correlation matrix has too many attributes.. unreadable
```
```{r}
# Remove highly correlated input variables
mrg8 <- mrg5

mrg8[, c("Total_Births", "Disabled_Medicare", "LBW")] <- NULL
```

```{r}
# mrg9 is the dataset with all the top correlated attributes across the target variables
mrg9 <- mrg8[, c("Lung_Cancer", "Smoker", "Obesity", "Whi_Cancer", "Blk_Cancer", "His_Cancer", "Oth_Cancer", "No_Exercise", "Brst_Cancer", "CHD", "Black", "White", "Blk_HeartDis", "Population_Size", "Over_40", "High_Blood_Pres", "Diabetes")]

mrgcor <- cor(mrg9)
corrplot::corrplot(mrgcor, title = "Health Correlation Plot")

```

```{r}
# Take a look at outliers
#summary(mrg8$Lung_Cancer) # 1st quartile is 49.40, 3rd quartile is 66.60
#summary(mrg8$Col_Cancer) # 1st quartile is 17.80, 3rd quartile is 22.60
#summary(mrg8$Brst_Cancer) # 1st quartile is 22.70, 3rd quartile is 28.50
#summary(mrg8$CHD) # 1st quartile is 149.6, 3rd quartile is 209.2

```

```{r}
#mrg9 <- mrg8
# Taking care of rows where there are outliers.
#mrg9 <- mrg9[(mrg9$Lung_Cancer< 66.6 & mrg9$Lung_Cancer>49.4),]

#mrg9 <- mrg9[(mrg9$Col_Cancer <22.6 & mrg9$Col_Cancer> 17.80),]

#mrg9 <- mrg9[(mrg9$Brst_Cancer < 28.50 & mrg9$Brst_Cancer > 22.70),]

#mrg9 <- mrg9[(mrg9$CHD < 209.2 & mrg9$CHD > 149.2),]

#boxplot(mrg9$CHD)
# Outliers removed

# Now redo correlative tests for target variables in Weka
```

```{r}
#library(foreign)
#write.arff(mrg8, file="CLEANDATA3.arff")

# Outlier removal didn't do anything to the correlation. Keep outliers?
# Yes because removing them causes our observables do go down to 110
```

```{r}
# Prevelance of cancer in total per race
whi_c = sum(mrg8$Whi_Cancer)
blk_c = sum(mrg8$Blk_Cancer)
his_c = sum(mrg8$His_Cancer)
oth_c = sum(mrg8$Oth_Cancer)
barplot(c(whi_c, blk_c, his_c, oth_c), names.arg = c("White", "Black", "Hispanic", "Other"), ylab = "Total Prevelance", main = "Total Deaths By Cancer Per Race", col = c("green", "yellow", "red", "darkblue"))
```

```{r}
# Total population per race
whi_cnt <- sum(mrg8$White)
blk_cnt <- sum(mrg8$Black)
his_cnt <- sum(mrg8$Hispanic)
oth_cnt <- sum(mrg8$Native_American + mrg8$Asian)
barplot(c(whi_cnt, blk_cnt, his_cnt, oth_cnt), names.arg = c("White", "Black", "Hispanic", "Other"), ylab = "Total Prevelance", main = "Total Population Per Race", col = c("green", "yellow", "red", "darkblue"))



```

```{r}
# Ratio of total cancer deaths/total deaths in sample (per race)
whi_rat <- whi_c/sum(mrg8$Total_Deaths, na.rm = TRUE)
blk_rat <- blk_c/sum(mrg8$Total_Deaths, na.rm = TRUE)
his_rat <- his_c/sum(mrg8$Total_Deaths, na.rm = TRUE)
oth_rat <- oth_c/sum(mrg8$Total_Deaths, na.rm = TRUE)

barplot(c(whi_rat, blk_rat, his_rat, oth_rat), names.arg = c("White", "Black", "Hispanic", "Other"), ylab = "Total Prevelance", main = "Total Deaths By Cancer Over Total Deaths Per Race", col = c("green", "yellow", "red", "darkblue"))


```

```{r}
# Total Deaths To Different Types of Cancers and Heart Disease
l_canc <- sum(mrg8$Lung_Cancer)
c_canc <- sum(mrg8$Col_Cancer)
b_canc <- sum(mrg8$Brst_Cancer)
#hrt <- sum(c(mrg8$Whi_HeartDis, mrg8$Blk_HeartDis, mrg8$His_HeartDis, mrg8$Oth_HeartDis))
hrt <- sum(mrg8$CHD)

barplot(c(l_canc, c_canc, b_canc, hrt), names.arg = c("Lung Cancer", "Colon Cancer", "Breast Cancer", "Heart Disease"), ylab = "Total Prevelance", main = "Total Deaths Per Cancer and Heart Disease", col = c("green", "yellow", "red", "darkblue"))

#barplot(c(sum(l_canc, c_canc, b_canc)/sum(mrg8$Total_Deaths), hrt/sum(mrg8$Total_Deaths)), names.arg = c("Cancer", "Heart Disease"), ylab = "Total Prevelance", main = "Ratio Of Disease Over Total Deaths", col = c("green", "red"))



```

```{r}

```


```{r}
# Prevelance of Heart Disease in total per race
whi_hrt <- sum(mrg8$Whi_HeartDis)
blk_hrt <- sum(mrg8$Blk_HeartDis)
his_hrt <- sum(mrg8$His_HeartDis)
oth_hrt <- sum(mrg8$Oth_HeartDis)

barplot(c(whi_hrt, blk_hrt, his_hrt, oth_hrt), names.arg = c("White", "Black", "Hispanic", "Other"), ylab = "Total Prevelance", main = "Total Deaths Due to Heart Disease", col = c("green", "yellow", "red", "darkblue"))

```


```{r}
# This is where I stopped, begin Univariate Analysis (check Progress)
# make another merge that includes state names from before
#whitedata <- mrg8[mrg8$White > (mrg8$Black + mrg8$Hispanic),]

cancers <- c(mrg8$Lung_Cancer, mrg8$Col_Cancer, mrg8$Brst_Cancer)
c_groups <- c(rep("Lung", 1261), rep("Col", 1261), rep("Brst", 1261))

c_aov <- aov(cancers ~ c_groups, data = mrg8)
summary(c_aov)
```


```{r}

```
```{r}

```


```{r}

```

```{r}
 
```

```{r}

```

```{r}

```{r}

```

